name: Build Fiddle
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    # Only run if the last commit does not start with [ci-skip]
    if: ${{ !contains(github.event.commits[0].message, '[ci-skip]') }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git user details
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches
      - name: Create Paperclip jar
        run: ./gradlew createReobfPaperclipJar
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v3
        with:
          name: Fiddle
          path: build/libs/fiddle-paperclip-*-reobf.jar
