#!/bin/sh

# Publishes the dev bundle to Maven local (in IntelliJ, right-click -> Run 'publishDevBundleToMavenLocal')

cd ..
./gradlew -PpublishDevBundle publishDevBundlePublicationToMavenLocal
cd gradle-bin
