#!/bin/sh

# Publishes the dev bundle and refreshes it as a dependency of the test plugin (in IntelliJ, right-click -> Run 'refreshTestPluginDevBundle')

./publishDevBundleToMavenLocal
cd ..
./gradlew :test-plugin:cleanAllPaperweightUserdevCaches
./gradlew :test-plugin:paperweightUserdevSetup
cd gradle-bin
